---
- name: This is the Highstate
  hosts: all
  become: true
  tasks:
    - name: Liste Partitions
      shell: lsblk
      register: listing_HD

    - name: Debug listing_HD
      debug:
        var: listing_HD

    - name: testing the debug multi line output
      debug: 
        msg: "Voici les partition {{ listing_HD.stdout_lines }}"

